import psycopg2

def create_category_table(cur, insert: bool = False):
    cur.execute('''
    CREATE TABLE IF NOT EXISTS category (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE
    );
    ''')
    if insert:
        insert_category_table(cur)

def create_dish_table(cur, insert: bool = False):
    cur.execute('''
    CREATE TABLE IF NOT EXISTS dish (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        price NUMERIC(8,2) NOT NULL CHECK (price > 0),
        category_id INT NOT NULL REFERENCES category(id) ON DELETE RESTRICT
    );
    ''')
    if insert:
        insert_dish_table(cur)

def insert_category_table(cur):
    cur.execute('''
    INSERT INTO category (id, name) VALUES
    (1,'Супы'),
    (2,'Салаты'),
    (3,'Горячее'),
    (4,'Десерты'),
    (5,'Напитки')
    ON CONFLICT (id) DO NOTHING;
    ''')

def insert_dish_table(cur):
    cur.execute('''
    INSERT INTO dish (title, price, category_id) VALUES
    ('Борщ', 250.00, 1),
    ('Солянка', 320.00, 1),
    ('Цезарь', 290.00, 2),
    ('Греческий салат', 270.00, 2),
    ('Паста карбонара', 450.00, 3),
    ('Куриная грудка гриль', 380.00, 3),
    ('Чизкейк', 190.00, 4),
    ('Медовик', 210.00, 4),
    ('Капучино', 150.00, 5),
    ('Морс клюквенный', 120.00, 5)
    ON CONFLICT DO NOTHING;
    ''')

def select_all_menu(cur):
    cur.execute('''
        SELECT d.title, d.price, c.name
        FROM dish d
        JOIN category c ON c.id = d.category_id
        ORDER BY c.id, d.id;
    ''')
    rows = cur.fetchall()
    for title, price, category in rows:
        print(f'{title} — {float(price):.2f} — {category}')

def select_prices(cur, min_price: float, max_price: float):
    cur.execute('''
        SELECT d.title, d.price, c.name
        FROM dish d
        JOIN category c ON c.id = d.category_id
        WHERE d.price BETWEEN %s AND %s
        ORDER BY d.price, d.id;
    ''', (min_price, max_price))
    rows = cur.fetchall()
    for r in rows:
        print(r)

def select_prefix(cur, pref: str):
    cur.execute('''
        SELECT d.title, d.price, c.name
        FROM dish d
        JOIN category c ON c.id = d.category_id
        WHERE d.title ILIKE %s
        ORDER BY d.title;
    ''', (pref + "%",))
    rows = cur.fetchall()
    for r in rows:
        print(r)

def select_cheap_dishes(cur, numb: int):
    cur.execute('''
        SELECT d.title, d.price, c.name
        FROM dish d
        JOIN category c ON c.id = d.category_id
        ORDER BY d.price ASC, d.id
        LIMIT %s;
    ''', (numb,))
    rows = cur.fetchall()
    for r in rows:
        print(r)

def select_cat_food(cur):
    cur.execute('''
        SELECT c.name, COUNT(d.id)
        FROM category c
        LEFT JOIN dish d ON c.id = d.category_id
        GROUP BY c.id, c.name
        ORDER BY c.id;
    ''')
    rows = cur.fetchall()
    for r in rows:
        print(r)

def contest_menu(cur):
    while True:
        print('Выберите нужную функцию:\n'
              '1) Показать всё меню\n'
              '2) Показать блюда в ценовом диапазоне\n'
              '3) Поиск по началу названия (префикс)\n'
              '4) Показать N самых дешёвых блюд\n'
              '5) Категории и количество блюд\n'
              '6) Выход\n')

        try:
            user_input = int(input('Введите номер: '))
        except ValueError:
            print('Ввести надо число 1-6')
            continue

        match user_input:
            case 1:
                select_all_menu(cur)  # красивый вывод через тире
            case 2:
                user_min = float(input('Введите минимальную цену: '))
                user_max = float(input('Введите максимальную цену: '))
                select_prices(cur, user_min, user_max)
            case 3:
                user_prefix = input('Введите префикс: ')
                select_prefix(cur, user_prefix)
            case 4:
                user_number = int(input('Введите целое число: '))
                select_cheap_dishes(cur, user_number)
            case 5:
                select_cat_food(cur)
            case 6:
                print('Выход из программы')
                break
            case _:
                print('Нет такого пункта')

try:
    with psycopg2.connect(
        dbname='task4',
        user='postgres',
        password='Damiano777!',
        host='localhost',
        port='5432'
    ) as conn:
        print('Успешное подключение к БД')
        with conn.cursor() as cur:
            create_category_table(cur, insert=True)
            create_dish_table(cur, insert=True)
            conn.commit()
            contest_menu(cur)
except Exception as e:
    print('Ошибка подключения к БД:', e)
